/*行业*/
var permission = {
    "data": [{
        "code": 100000,
        "name": "互联网/IT/电子/通信",
        "subLevelModelList": [{
            "code": 100001,
            "name": "电子商务",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100002,
            "name": "游戏",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100003,
            "name": "媒体",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100004,
            "name": "广告营销",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100005,
            "name": "数据服务",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100006,
            "name": "医疗健康",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100007,
            "name": "生活服务",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100008,
            "name": "O2O",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100009,
            "name": "旅游",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100010,
            "name": "分类信息",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100011,
            "name": "音乐/视频/阅读",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100012,
            "name": "在线教育",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100013,
            "name": "社交网络",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100014,
            "name": "人力资源服务",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100015,
            "name": "企业服务",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100016,
            "name": "信息安全",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100017,
            "name": "新零售",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100018,
            "name": "智能硬件",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100019,
            "name": "移动互联网",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100020,
            "name": "互联网",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100021,
            "name": "计算机软件",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100022,
            "name": "计算机硬件",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100023,
            "name": "计算机服务",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100024,
            "name": "通信/网络设备",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100025,
            "name": "运营商/增值服务",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100026,
            "name": "电子/半导体/集成电路",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 100100,
        "name": "广告/传媒/文化/体育",
        "subLevelModelList": [{
            "code": 100101,
            "name": "广告/公关/会展",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100102,
            "name": "新闻/出版",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100103,
            "name": "广播/影视",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100104,
            "name": "文化/体育/娱乐",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 100200,
        "name": "金融",
        "subLevelModelList": [{
            "code": 100201,
            "name": "银行",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100202,
            "name": "保险",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100203,
            "name": "证券/期货",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100204,
            "name": "基金",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100205,
            "name": "信托",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100206,
            "name": "互联网金融",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100207,
            "name": "投资/融资",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100208,
            "name": "租赁/拍卖/典当/担保",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 100300,
        "name": "教育培训",
        "subLevelModelList": [{
            "code": 100301,
            "name": "学前教育",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100302,
            "name": "院校",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100303,
            "name": "培训机构",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {"code": 100304, "name": "学术/科研", "subLevelModelList": null, "firstChar": null, "pinyin": null, "rank": 0}],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 100400,
        "name": "制药/医疗",
        "subLevelModelList": [{
            "code": 100401,
            "name": "制药",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100402,
            "name": "医疗/护理/卫生",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100403,
            "name": "医疗设备/器械",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 100500,
        "name": "交通/物流/贸易/零售",
        "subLevelModelList": [{
            "code": 100501,
            "name": "交通/运输",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100502,
            "name": "物流/仓储",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100503,
            "name": "批发/零售",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {"code": 100504, "name": "贸易/进出口", "subLevelModelList": null, "firstChar": null, "pinyin": null, "rank": 0}],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 100600,
        "name": "专业服务",
        "subLevelModelList": [{
            "code": 100601,
            "name": "咨询",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100602,
            "name": "法律",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100603,
            "name": "翻译",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100604,
            "name": "人力资源服务",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100605,
            "name": "财务/审计/税务",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100606,
            "name": "检测/认证",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100607,
            "name": "专利/商标/知识产权",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {"code": 100608, "name": "其他专业服务", "subLevelModelList": null, "firstChar": null, "pinyin": null, "rank": 0}],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 100700,
        "name": "房地产/建筑",
        "subLevelModelList": [{
            "code": 100701,
            "name": "房地产开发",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100702,
            "name": "工程施工",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100703,
            "name": "建筑设计",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100704,
            "name": "装修装饰",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100705,
            "name": "建材",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100706,
            "name": "地产经纪/中介",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {"code": 100707, "name": "物业服务", "subLevelModelList": null, "firstChar": null, "pinyin": null, "rank": 0}],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 100800,
        "name": "汽车",
        "subLevelModelList": [{
            "code": 100801,
            "name": "汽车生产",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100802,
            "name": "汽车零部件",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100803,
            "name": "4S店/后市场",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 100900,
        "name": "机械/制造",
        "subLevelModelList": [{
            "code": 100901,
            "name": "机械设备/机电/重工",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100902,
            "name": "仪器仪表/工业自动化",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100903,
            "name": "原材料及加工/模具",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100904,
            "name": "印刷/包装/造纸",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 100905,
            "name": "船舶/航空/航天",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 101000,
        "name": "消费品",
        "subLevelModelList": [{
            "code": 101001,
            "name": "食品/饮料/烟酒",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101002,
            "name": "日化",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101003,
            "name": "服装/纺织/皮革",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101004,
            "name": "家具/家电/家居",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101005,
            "name": "玩具/礼品",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101006,
            "name": "珠宝/首饰",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101007,
            "name": "工艺品/收藏品",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101008,
            "name": "办公用品及设备",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 101100,
        "name": "服务业",
        "subLevelModelList": [{
            "code": 101101,
            "name": "餐饮",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101102,
            "name": "酒店",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101103,
            "name": "旅游",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101104,
            "name": "美容/美发",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101105,
            "name": "婚庆/摄影",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {"code": 101106, "name": "其他服务业", "subLevelModelList": null, "firstChar": null, "pinyin": null, "rank": 0}],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 101200,
        "name": "能源/化工/环保",
        "subLevelModelList": [{
            "code": 101201,
            "name": "石油/石化",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101202,
            "name": "化工",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101203,
            "name": "矿产/地质",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101204,
            "name": "采掘/冶炼",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101205,
            "name": "电力/热力/燃气/水利",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101206,
            "name": "新能源",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {"code": 101207, "name": "环保", "subLevelModelList": null, "firstChar": null, "pinyin": null, "rank": 0}],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }, {
        "code": 101300,
        "name": "政府/非盈利机构/其他",
        "subLevelModelList": [{
            "code": 101301,
            "name": "政府/公共事业",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101302,
            "name": "非盈利机构",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {
            "code": 101303,
            "name": "农/林/牧/渔",
            "subLevelModelList": null,
            "firstChar": null,
            "pinyin": null,
            "rank": 0
        }, {"code": 101304, "name": "其他行业", "subLevelModelList": null, "firstChar": null, "pinyin": null, "rank": 0}],
        "firstChar": null,
        "pinyin": null,
        "rank": 0
    }], "resmsg": "请求成功", "rescode": 1
}

export default {
    permission
}